"""Stable numeric exit codes contract for Trace CLI."""

EXIT_SUCCESS = 0
EXIT_ERROR = 1
EXIT_USAGE_ERROR = 2
EXIT_SAFETY_GATE_FAILED = 10
EXIT_HASH_MISMATCH = 11
EXIT_NOT_FOUND = 12
EXIT_INSUFFICIENT_STORAGE = 13
EXIT_PERMISSION_DENIED = 14
